services:
  vite_app:
    build:
      context: .
      dockerfile: Dockerfile-dev
      target: development
    container_name: vue3-primevue-tailwindcss
    volumes:
      - './src:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

volumes:
  node_modules:
